# env:
#   global:
#     - CC_TEST_REPORTER_ID=47cc3c19b33fda0e5a36368db290f998af17536481fa02286df3a77b7360c61d

sudo: false
language: node_js
node_js:
  - 8

# before_script:
#   - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
#   - chmod +x ./cc-test-reporter
#   - ./cc-test-reporter before-build

script:
  - yarn build
  - yarn nyc
  - cd client && yarn test-ci

after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token cd client && yarn coveralls
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token yarn coveralls
  # - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
