sudo: false
language: node_js
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

node_js:
  - 8
  - 9

 before_install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi

script:
  - yarn build
  - yarn nyc
  - cd client && yarn test-ci
  - cd ..

after_script:
  - cp ./client/coverage/lcov.info ./coverage/lcov_1.info
  - mv ./coverage/lcov.info ./coverage/lcov_2.info
  - ./node_modules/.bin/lcov-result-merger './coverage/lcov_*.info' './coverage/coverage_merged.log'
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token yarn coveralls
